### ISSUE TITLE
WMS GetLegendGraphic requests fail

### ISSUE THREAD

**Issue by asedgmen** [nci/gsky#15]
The WMS GetCapabilities statement provides a LegendURL for all layers (at http://gsky.nci.org.au/ows), although GetLegendGraphic requests fail with a 500 status response for all layers except the two DEA Intertidal Extents layers.  Error message is: 

> open : no such file or directory

**Comment by prl900** [comment]
As far as I know, True and False colour Landsat composites do not have legends or color scales associated with them. I will continue this bug thread assuming that the problem is that the http response for a resource not found should be 404 instead of 500. Let us know if this is not the intention.

https://github.com/nci/gsky/blob/24610a42286a139cea63d7950f671ed66b436f49/ows.go#L266

Should check for the existence of a Legend file in the config file for that layer and respond with 404 error message if not found>

**Comment by asedgmen** [comment]
The issue here is that the GetCaps is advertising legends that do not exist.   I suggest excluding the LegendURL elements in the GetCapabilities statement from those layers that do not have a legend (it's not mandatory in the XML Schema).  This should prevent requests for the legend graphic from occurring in the first place, although if a user makes a request anyway, then yes, I think a 404 status response would be more appropriate than a 500.

**Comment by bje-** [comment]
@edisonguo reports this is fixed.
