### ISSUE TITLE
WMS not working in QGIS

### ISSUE THREAD

**Issue by kdruken** [nci/gsky#27]
When adding WMS layer in QGIS using full GetMap request (http://gsky.nci.org.au/ows?layers=LS7%3ANBAR%3ATRUE&styles=&crs=EPSG%3A4326&bgcolor=0xFFFFFF&height=256&width=256&version=1.3.0&bbox=-35.3075%2C149.12441666666666%2C-35.1%2C151&time=1999-08-05T00%3A00%3A00.000Z&transparent=FALSE), an error message is displayed when trying to add any available layer. Seems to be trying to make a GetLegend request based on the part of the error message visible (error message gets cut off... will try and put screenshot if able):

> Error downloading http://gsky.nci.org.au/ows?service=WMS&request=GetLeg 

(Note: tested from QGIS 2.14.8-Essen and 2.18.2 Las Palmas)
![screen shot 2018-05-30 at 10 22 27 am](https://user-images.githubusercontent.com/12436691/40692179-97688ca0-63f3-11e8-8c07-9646dce87381.png)

**Comment by prl900** [comment]
Current version of GSKY can serve legends using the `request=GetLegendGraphic` url parameter. I've checked current WMS [specs](http://portal.opengeospatial.org/files/?artifact_id=14416) and it does not list `GetLegendGraphic` nor `GetLeg` as standard functionality.

I think Geoserver implements `request=GetLegendGraphic` for publishing color scales and legends, which is what TerriaJS consumes, but I think it's their own standard.

Solving this issue could be as simple as adding `GetLeg` as an alternative name for the legends functionality in the WMS switch clause at `ows.go`. We need to try if the output format is the same as with Geoserver legends and if `GetLeg` is QGis specific.

**Comment by asedgmen** [comment]
This appears to be related to issue https://github.com/nci/gsky/issues/15 that I raised, whereby the GetCaps document advertises URLs to legend graphics that don't exist.  QGIS looks in the GetCaps document to obtain the legend graphic URL when loading the WMS layer, and is failing on the ones provided with this service because they don't exist.

I'm pretty sure that "GetLeg" above is just "GetLegendGraphic" in the QGIS error message being cutoff, i.e. I don't think QGIS is issuing a "GetLeg" request.

Note that the GetLegendGraphic operation is part of the OGC "[Styled Layer Descriptor profile of the Web Map Service Implementation Specification](http://www.opengeospatial.org/standards/sld)".

**Comment by kdruken** [comment]
@prl900 - apologies, sorry for confusion and not being more clear. Believe that it's just cutoff and is the GetLegend as @asedgmen says above. 

Had a feeling it was probably related to one of those OGC issues- thanks @asedgmen!

**Comment by juan-guerschman** [comment]
I had the same issue today (I think): 
QGis V3.0.3. 
![image](https://user-images.githubusercontent.com/8801702/41761119-80164936-7639-11e8-9f4a-b0d04484d15d.png)
