### ISSUE TITLE
`landsat8_nbar_16day` available styles

### ISSUE THREAD

**Issue by khornlund** [nci/gsky#316]
Hi,

As shown in cell 7 of the documentation [here](https://gsky.readthedocs.io/en/latest/_notebook/Notebook_GSKY_WCS.html), the `landsat8_nbar_16day` layer does not report any available styles.

However if you do not include `Style='fc'` in your request, you get a `WCS style not specified` error.

Could this be made clearer? Are there other styles available? What does 'fc' mean?

Thanks,
Karl

**Comment by edisonguo** [comment]
The available styles are `tc` and `fc`. `tc` stands for true colour which is the `red`, `green` and `blue` bands in the underlying netcdf data files. `fc` stands for false colour which is the `swir1`, `nir` and `green` bands in the underlying data files.

**Comment by khornlund** [comment]
Ok, thanks for clearing that up. 

Do you think this information could be provided when users query for available styles as in cell 7 of the example notebook? Eg.

```
print(wcs[layer].styles)
```

**Comment by edisonguo** [comment]
The `styles` parameter is not part of WCS standard and that's why `wcs[layer]` doesn't include the `styles` information. The WCS facility in TerriaJS, however, goes through the WMS pipeline to invoke WCS. When we build WCS as a collaboration project with Terria, we will have to include `styles` in the WCS url to be compatible with Terria. https://github.com/TerriaJS/terriajs/pull/3170

Having said that, `styles` can be queried from WMS GetCaps XML response: 
https://gsky.nci.org.au/ows/dea?service=WMS&request=GetCapabilities&version=1.3.0&tiled=true
