### ISSUE TITLE
Can't get the Jupyter examples to work

### ISSUE THREAD

**Issue by rbeucher** [nci/gsky#386]
Hi,

I have been trying to use the services using owslib and the jupyter examples provided here https://github.com/nci-training/gsky-demos.

I can't get any of the example to return an image.

Here is the kind of request generated by WebMapService:

http://gsky.nci.org.au/ows/dea?SERVICE=WMS&service=WMS&version=1.3.0&request=GetMap&layers=landsat8_nbart_daily&styles=&width=256&height=256&crs=EPSG%3A4326&bbox=-37%2C147%2C-35%2C148&format=image%2Fpng&transparent=FALSE&bgcolor=0xFFFFFF&exceptions=XML&time=2013-03-21T00%3A00%3A00.000Z&Styles=tc

Just a black image...

Any suggestions?

Thanks!

**Comment by edisonguo** [comment]
@rbeucher this is because there is no data corresponding to the `bbox` and `time` parameters in the request. It's likely that the authors of the notebook hasn't kept up to date. I'll let them know about this issue. Thanks for pointing it out.

Having said that, an easy and general way to find a working example URL goes like this:

* Open https://terria-cube.terria.io/ which is a mapping visualisation tool

* Click on `Add Data` (big blue button on the left panel) -> `My Data` (the tab on top) -> `Add web data`

* Type https://gsky.nci.org.au/ows/dea (make sure no leading/trailing spaces) and click on `Add`

* You will see a list of layers now. The URL you posted corresponds to `Daily DEA Landsat 8 terrian corrected surface reflectance`.  Click on this layer and then click on the `Add to the map` button on top right.

* Once this layer gets added to the map, you're likely to see "Zoom in to view..." across the screen. You can either roll your mouse wheel or click on the +/- button on the right of the window to zoom in and out to see the actual satellite images. You can also navigate through time using the time control buttons on the left panel.

* If you use Google Chrome, you can open DevTools to inspect the requested URLs for each tile. For example, I got this one working: https://gsky.nci.org.au/ows/dea?time=2019-01-01T00%3A00%3A00.000Z&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=landsat8_nbart_daily&bbox=13149614.84995544%2C-2504688.542848654%2C13775786.985667605%2C-1878516.4071364924&width=256&height=256 Other browsers should be similar.
