### ISSUE TITLE
WCS specify returned bands

### ISSUE THREAD

**Issue by pbranson** [nci/gsky#464]
I have has a play with the notebooks and streaming WCS request data into XArray objects using fsspec with reasonable success:

```
import fsspec
import xarray as xr
import matplotlib.pyplot as plt

gsky_url = 'http://gsky.nci.org.au/ows/dea'

wcs = WebCoverageService(gsky_url, version='1.0.0')

layer = "sentinel2_nbart_daily"
subset_bbox = (117.5,-32.5,118.,-33.)

t=wcs[layer].timepositions[-48]

print(t + '\n')
output = wcs.getCoverage(identifier=layer, Styles='fc', 
                         time=[t],
                         bbox=subset_bbox,format='NetCDF',
                         crs='EPSG:4326', width=1024, height=1024)
print('Request URL: ' + output.geturl() + '\n')

with fsspec.open(output.geturl()) as f:
    ds = xr.open_dataset(f)
    print(ds)
    print('\nVariable Attributes:')
    for v in ds.data_vars:
        print(v)
        print(ds[v].attrs)
```

Which outputs:

```
2020-05-28T00:00:00.000Z

Request URL: http://gsky.nci.org.au/ows/dea?version=1.0.0&request=GetCoverage&service=WCS&Coverage=sentinel2_nbart_daily&BBox=117.5%2C-32.5%2C118.0%2C-33.0&time=2020-05-28T00%3A00%3A00.000Z&crs=EPSG%3A4326&format=NetCDF&width=1024&height=1024&Styles=fc

<xarray.Dataset>
Dimensions:  (lat: 1024, lon: 1024)
Coordinates:
  * lat      (lat) float64 -32.5 -32.5 -32.5 -32.5 ... -33.0 -33.0 -33.0 -33.0
  * lon      (lon) float64 117.5 117.5 117.5 117.5 ... 118.0 118.0 118.0 118.0
Data variables:
    Band1    (lat, lon) float32 ...
    Band2    (lat, lon) float32 ...
    Band3    (lat, lon) float32 ...
    crs      |S1 ...
Attributes:
    Conventions:  CF-1.5
    GDAL:         GDAL 3.0.1, released 2019/06/28
    history:      Mon Aug 10 18:25:17 2020: GDAL Create( /local/gsky-tmp/rast...

Variable Attributes:
Band1
{'long_name': 'GDAL Band Number 1', 'grid_mapping': 'crs'}
Band2
{'long_name': 'GDAL Band Number 2', 'grid_mapping': 'crs'}
Band3
{'long_name': 'GDAL Band Number 3', 'grid_mapping': 'crs'}
crs
{'grid_mapping_name': 'latitude_longitude', 'long_name': 'CRS definition', 'longitude_of_prime_meridian': array([0.]), 'semi_major_axis': array([6378137.]), 'inverse_flattening': array([298.25722356]), 'spatial_ref': 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]', 'GeoTransform': '117.5 0.00048828125 0 -33 0 0.00048828125 '}
```

Not a lot of meta-data about what the returned bands are - is it possible to specify the bands in the request?
Is it possible to request the data at native resolution? Or specify the resampling method?
How do you identify dates with scenes available in the defined bbox, at present the request just returns a NetCDF file with a single band filled with NaNs.

**Comment by edisonguo** [comment]
"is it possible to specify the bands in the request?" - GSKY WCS was built as a contractual deliverable to work with Terria's clip-n-ship feature. How it was set up was to tightly integrate with WMS by sharing WMS processing pipeline as much as possible. Essentially the parameters in WMS `GetMap` becomes 
 equivalence in WCS `GetCoverage`. Officially it is not possible to specify returned bands in the request. The set of returned bands are fixed as per `style` despite `style` is not in WCS standard. Having said that, we're looking at specifying returned bands on our roadmap as more and more users want WCS to go beyond Terria.

"Is it possible to request the data at native resolution?" - This is not possible because the full resolution of satellite imagery datasets is too big to return. Downsampling is virtually always required. For a workaround for higher resolution, you can try to reduce the spatial extent of the bounding box while keeping the width and height fixed.

"Or specify the resampling method?" - As discussed previously, WCS and WMS share much of the processing pipeline. We have no plan to support resampling methods in addition to nearest neighbour at this time.

**Comment by pbranson** [comment]
Thanks for the prompt response. 

Will be interested to see how the WCS service develops for uses beyond the delivery of web-mapping.
