### ISSUE TITLE
Support for categorical colorscale

### ISSUE THREAD

**Issue by erick-otenyo** [nci/gsky#532]
Hello

Is there a way to define a categorical colorscale based on the raster values ? Lets say you have some threshold values and you would like you wms map to be styled based on the values.

For example:
 if value <= 0, assign color #FFFFFF
 if value <= 1 assign color #FFFE91
....

For now I see you define a pallete with options to interpolate or not. 

How can the categorical colorscale be approached ?

Thanks

**Comment by edisonguo** [comment]
There is no built-in support for categorical colorscale at the moment. However we do encounter categorical colorscale problems in our own deployment. Our solution is as follows:
1) set interpolate to false
2) write a python script to generate the 256 RGB entries for the categories

**Comment by erick-otenyo** [comment]
Thank you for your response. I will try the workaround and see how it goes.

Thanks!

**Comment by erick-otenyo** [comment]
@edisonguo I will appreciate if you can share a sample of the python script. Thanks

**Comment by edisonguo** [comment]
Previously I forgot to mention that there are addition fields important for WMS images - `offset_value` and `clip_value`.  Basically the raw data values go through a transformation process to scale into [0, 255] in order to generate a valid PNG image. The transformation process works using the following formula:

`PNG pixel value = clip(raw data value + offset_value, clip_value) / clip_value * 255`

A good heuristic starting point is to use the min and max of your raw data values for `offset_value` and `clip_value` to get an image with basic looking. The look and feel the image (e.g. image contrast) can then be adjusted by varying those values.

Having said that, the RGBA values in the config are applied after the transformation, which means the input domain to the colour rendering is always [0, 255]. Here is a sample python script that generates the RGBA values for three categories - [0, 10), (100, 200) and everything else. 

```
import json

colours = []
for i in range(256):
  if i < 10: 
    rgba = {"R": 217, "G": 150, "B": 148, "A": 255}
  elif i > 100 and i < 200:
    rgba = {"R": 112, "G": 112, "B": 112, "A": 255}
  else:
    rgba = {"R": 79, "G": 129, "B": 189, "A": 255}
  colours.append(rgba)

print(json.dumps(colours, indent=2))
```

**Comment by erick-otenyo** [comment]
Thank you very much @edisonguo. This helped me to understand and I got the desired results!
